export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const AUTH_USER = 'AUTH_USER'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const LOGOUT_USER = 'LOGOUT_USER'

// TODO: updateUser
export const UPDATE_USER = 'UPDATE_USER_BEGIN';
export const UPDATE_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_FAILED = 'UPDATE_USER_ERROR';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';