export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER = 'REGISTER_USER'
export const REG_SUCCESS = 'REGISTER_SUCCESS'
export const REG_FAIL = 'REGISTER_FAIL'

export const LOGIN_USER = 'LOGIN_USER'